### ISSUE TITLE
数据预处理页面建议通过人机交互设定外边框

### ISSUE THREAD

**Issue by xianchun** [CoinLQ/SegmentationCheck#3]
1、图像预处理页面
    在图片预处理页面中，对于切栏所设定的的外边框形状，可以菜单设定（如矩形、梯形），矩形大小的调整就用目前的方法，通过鼠标拖动4个顶点。对于梯形，可以移动矩形外框的4个顶点，仅在线段方向上，上下、左右移动。

2、文字预处理
    如果要对歪斜的文本进行扭曲矫正，除了矩形和梯形外边框外，可能还需要设置多边形外框，通过鼠标选取外边框上的控制点，按下鼠标，移动控制点，拽着与该点相连的线段一起移动，调整选定的控制点，直到获得所需的外框形状，并保存多边形端点坐标。

**Comment by lvpython** [comment]
@xianchun 多谢给予的细节思考。看后期数据的情况，如果人工调整作为重点，我们会考虑把多边形调整加上的。

**Comment by xianchun** [comment]
收到。随喜！


    对了，我们放到Github上的代码，就是截图里的这个配置的密码，前段时间给周轶师兄介绍这个平台时，她说公布出来不好，可能会受到攻击，不知要不要紧？


 [cid:2b4f3bdb-5d44-4077-b612-87c0ac40e60b]





--------------------

祝六时吉祥！

末学贤淳合十敬上






________________________________
发件人: Cheung Huiyong <notifications@github.com>
发送时间: 2016年11月9日 12:33
收件人: CoinLQ/SegmentationCheck
抄送: xianchun; Mention
主题: Re: [CoinLQ/SegmentationCheck] 数据预处理页面建议通过人机交互设定外边框 (#3)


@xianchun<https://github.com/xianchun> 多谢给予的细节思考。看后期数据的情况，如果人工调整作为重点，我们会考虑把多边形调整加上的。

―

**Comment by lvpython** [comment]
没有看到截图，是不是说数据库的配置密码？

**Comment by xianchun** [comment]
是的。 SECREK_KEY


--------------------

祝六时吉祥！

末学贤淳合十敬上






________________________________
发件人: Cheung Huiyong <notifications@github.com>
发送时间: 2016年11月17日 0:51
收件人: CoinLQ/SegmentationCheck
抄送: xianchun; Mention
主题: Re: [CoinLQ/SegmentationCheck] 数据预处理页面建议通过人机交互设定外边框 (#3)


没有看到截图，是不是说数据库的配置密码？

―

**Comment by lvpython** [comment]
明白了。KEY已经换成环境变量了，感谢。
